// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdtv1JI4abaDMz5-lX9J5a9CLILOM_nvI',
    appId: '1:350266614683:web:37717e3798c46997c7f73e',
    messagingSenderId: '350266614683',
    projectId: 'rainn-app-v2',
    authDomain: 'rainn-app-v2.firebaseapp.com',
    storageBucket: 'rainn-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATOIOTahtsvDJxTqBe5NUaq-J9Hj1-Ghs',
    appId: '1:350266614683:android:a4095e85fa548373c7f73e',
    messagingSenderId: '350266614683',
    projectId: 'rainn-app-v2',
    storageBucket: 'rainn-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVqeTWYIA4bvjhbwBpebB6aNIwioYvV2o',
    appId: '1:350266614683:ios:5509064a296bea09c7f73e',
    messagingSenderId: '350266614683',
    projectId: 'rainn-app-v2',
    storageBucket: 'rainn-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.rainnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdtv1JI4abaDMz5-lX9J5a9CLILOM_nvI',
    appId: '1:350266614683:web:549a119d54d0fab6c7f73e',
    messagingSenderId: '350266614683',
    projectId: 'rainn-app-v2',
    authDomain: 'rainn-app-v2.firebaseapp.com',
    storageBucket: 'rainn-app-v2.firebasestorage.app',
  );
}
